import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';
import dotenv from 'dotenv';
import { GoogleGenAI, Modality } from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Lazy initialize Gemini client with required headers
function getGeminiClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not set');
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });
}

// Health endpoint
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Text-to-Speech API using gemini-3.1-flash-tts-preview
app.post('/api/tts', async (req, res) => {
  try {
    const { text, voice = 'Puck', promptPrefix = '' } = req.body;
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ error: 'Text prompt is required' });
    }

    const ai = getGeminiClient();
    const spokenText = promptPrefix ? `${promptPrefix}: ${text}` : text;

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-tts-preview',
      contents: [{ parts: [{ text: spokenText }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: voice, // 'Puck', 'Charon', 'Kore', 'Fenrir', 'Zephyr'
            },
          },
        },
      },
    });

    const part = response.candidates?.[0]?.content?.parts?.[0];
    const base64Audio = part?.inlineData?.data;
    const mimeType = part?.inlineData?.mimeType || 'audio/pcm;rate=24000';

    if (!base64Audio) {
      return res.status(500).json({ error: 'No audio generated by the model' });
    }

    return res.json({
      audioData: base64Audio,
      mimeType,
      sampleRate: 24000,
    });
  } catch (error: any) {
    console.error('Error generating TTS:', error);
    return res.status(500).json({
      error: error?.message || 'Failed to generate speech audio',
    });
  }
});

// Creative AI Copilot for Sattu's Concepts & Trading Logic
app.post('/api/ask-ai', async (req, res) => {
  try {
    const { prompt, context } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const ai = getGeminiClient();
    const systemInstruction = `You are Sattu's AI Thinking Partner and Concept Co-architect. 
Sattu is a 17-year-old creator, singer, trader, and aspiring entrepreneur.
His proprietary trading concept is MSCC (Mirror Smart Code Crackr) - analyzing market symmetry, liquidity pools, mirror reaction zones, and algorithmic price fractals in Crypto and Forex.
His visionary project is CCX (Chart Cracker X) - an all-in-one platform integrating interactive charts, smart journal, trading analytics, concept backtesting, and AI insights.
His music identity is "Sattu Singer", creating soulful, ambitious, and authentic tracks.
His mindset: Discipline, consistency, learning from mistakes, continuous execution, and writing his own story.

Respond concisely, inspiringly, and with sharp technical and analytical clarity in fluent Hinglish/English with high energy and deep respect for Sattu's vision.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.7-flash',
      contents: `${context ? `[Context: ${context}]\n\n` : ''}${prompt}`,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    return res.json({
      text: response.text || '',
    });
  } catch (error: any) {
    console.error('Error querying AI:', error);
    return res.status(500).json({
      error: error?.message || 'Failed to process AI query',
    });
  }
});

// Vite middleware for development vs static files in production
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Sattu Singer CCX Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
